# Generated by Django 5.2 on 2025-04-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_montana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='manager',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
