# Generated by Django 5.2 on 2025-04-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_montana', '0002_alter_employee_image_url_alter_manager_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
