# Generated by Django 5.2 on 2025-04-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_montana', '0003_alter_employee_image_url_alter_manager_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
