# Generated by Django 5.2 on 2025-04-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_montana', '0004_alter_employee_image_url_alter_manager_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department_pk',
            new_name='department',
        ),
    ]
